const RIZAL=["Dr. Jose Rizal","The National Hero","1861–1896","The National Hero, Polymath & Patriot",
"An ophthalmologist, novelist, sculptor, linguist, and educator, Dr. Jose Rizal stands as the central figure of Philippine nationalism. Through his groundbreaking novels Noli Me Tángere and El Filibusterismo, he diagnosed the social ills of Spanish colonial rule with literary precision. His commitment to peaceful reform, intellectual enlightenment, and national self-determination ultimately sparked a revolution, sealing his legacy through martyrdom at Bagumbayan.",
"Born on June 19, 1861, in Calamba, Laguna, to Francisco Mercado and Teodora Alonso; educated at the Ateneo Municipal de Manila, Universidad de Santo Tomas, and Universidad Central de Madrid; a true polymath fluent in over 20 languages with expertise spanning medicine, fine arts, land surveying, and agricultural engineering.",
"Key leader of the Propaganda Movement in Europe and founder of La Liga Filipina; transformed his four-year exile in Dapitan (1892–1896) into a model of community development, public health, and progressive education; his execution on December 30, 1896, galvanized the Katipunan revolution and cemented his enduring status as the premier national hero of the Philippines.",
"Historical Impact & Legacy"];
/* Museum content. Edit here to change people, rooms or the timeline.
   Portrait fields: [room key, name, short label (wall plaque), years, classification, museum plaque, personal background, connection to Rizal] */
const P=[
["y", "Teodora Alonso Realonda", "Mother and first teacher", "1827–1911", "The Matriarch & Primary Educator", "A highly educated scholar of Colegio de Santa Rosa, Doña Teodora was a skilled businesswoman, mathematician, and literature enthusiast. As Jose Rizal’s mother and first teacher, her moral guidance shaped his early intellect. Her traumatic arrest and forced 50-kilometer walk under Spanish colonial authorities served as the young hero's initial awakening to systemic injustice.", "Born into the prominent Quintos-Realonda family in Manila; managed the family's agricultural and commercial enterprises in Calamba, Laguna.", "Taught Rizal reading, Spanish, and poetry; corrected his early poems; her public persecution transformed his private affection into lifelong anti-colonial advocacy."],
["y", "Segunda Katigbak", "First romance", "", "The First Romance", "A 14-year-old aristocrat from Lipa, Batangas, Segunda Katigbak captured the heart of a 16-year-old Jose Rizal during his early student days in Manila. Their brief, hesitant romance represents the innocent heartbreak of the hero's youth.", "Wealthy boarding student at La Concordia College in Manila.", "Rizal’s first romantic infatuation; despite mutual affection, she was already betrothed to Manuel Luz, leading to their quiet separation."],
["y", "Leonor Rivera", "The eternal muse", "", "The Eternal Muse & Archetype for \"Maria Clara\"", "Refined, musical, and fiercely loyal, Leonor Rivera was Rizal’s childhood sweetheart and cousin. Their secret 11-year correspondence endured political exile and distance, ultimately serving as Rizal's primary real-life inspiration for the tragic character of Maria Clara in Noli Me Tángere.", "Native of Camiling, Tarlac; daughter of Antonio Rivera (Rizal’s uncle and landlord in Manila).", "Communicated secretly using the pen name \"Taimis\"; her mother intercepted Rizal's letters due to his dangerous political status, forcing Leonor into a tragic marriage with English engineer Henry Kipping."],
["a", "Consuelo Ortiga y Pérez", "Madrid companion", "", "The Madrid Expatriate Companion", "The daughter of Don Pablo Ortiga y Rey (former mayor of Manila), Consuelo hosted Madrid's vibrant social gatherings for Filipino ilustrados. Her poise and intellect provided emotional comfort to Rizal during his solitary student years in Spain.", "Spanish socialite whose Madrid residence served as a central meeting place for Filipino expatriates and reformers.", "Inspired Rizal’s poem A La Señorita C.O.y.P.; Rizal stepped back from pursuing a deeper relationship out of loyalty to his engagement with Leonor Rivera and respect for his friend Eduardo de Lete."],
["a", "Seiko Usui (O-Sei-San)", "Companion in Tokyo", "", "The Japanese Intellectual Companion", "Fluent in English and French, O-Sei-San was a cultured daughter of a former samurai. During Rizal’s 1888 stay in Tokyo, she served as his cultural guide, Japanese language tutor, and trusted companion.", "Independent scholar living in Tokyo with deep knowledge of traditional Japanese arts and Kabuki theater.", "Introduced Rizal to Japanese culture; Rizal considered settling permanently in Japan with her, but chose to leave to pursue his nationalistic mission for the Philippines."],
["a", "Gertrude Beckett", "London assistant", "", "The London Assistant (\"Pettie\")", "Daughter of Rizal's landlord in London, Gertrude Beckett assisted the Filipino scholar while he conducted historical research at the British Museum, helping him mix art pigments and prepare clay for his sculptures.", "Eldest daughter of Charles Beckett, living in London’s Primrose Hill neighborhood.", "Affectionately called him \"Pettie\"; fell deeply in love with Rizal, prompting him to move abruptly to Paris to avoid taking advantage of her unrequited feelings."],
["a", "Suzanne Jacoby", "Brussels caretaker", "", "The Brussels Caretaker", "Suzanne Jacoby cared for Rizal during his frugal months in Belgium while he labored over his second political novel, El Filibusterismo. Her surviving letters capture a deep emotional attachment during one of Rizal's most financially strained periods.", "Belgian resident who managed a modest boarding house in Brussels alongside her aunts.", "Maintained an affectionate correspondence with Rizal after he left Belgium; Rizal remained focused on novel publication and his family's eviction crisis in Calamba."],
["a", "Nellie Boustead", "Anglo-Filipina scholar", "", "The Anglo-Filipina Scholar", "Educated, wealthy, and a skilled fencer, Nellie Boustead challenged and captivated Rizal during his time in France. Their romantic courtship nearly led to marriage, highlighting Rizal's search for an intellectual peer.", "Daughter of wealthy Anglo-Filipino merchant Eduardo Boustead; raised in Paris and Biarritz as a devout Protestant.", "Nearly triggered a duel between Rizal and Antonio Luna; marriage plans collapsed when Rizal refused to convert to Protestantism and her mother objected to his political risk."],
["d", "Josephine Bracken", "Exile's wife", "", "The Exile's Wife & Revolutionary Ally", "An Irish woman raised in Hong Kong, Josephine Bracken arrived in Dapitan seeking medical aid for her adoptive father. She became Jose Rizal’s common-law wife during his exile, remaining steadfast by his side through his final trial and execution before joining the Katipunan revolution.", "Born in Hong Kong to Irish parents; adopted by American engineer George Taufer.", "Lived with Rizal in Dapitan as his wife after local clergy refused a formal marriage; gave birth to a premature son, Francisco, who survived only hours; cared for wounded Filipino revolutionaries following Rizal’s death."]
];

/* Rooms: [key, name, subtitle, depth]. Portraits use the key in their first field. */
const ROOMS=[["f","Foyer","Rizal's life in eight moments",9],["y","Calamba and Manila","1861–1882: Family and first loves",13],["a","Abroad","1882–1891: Spain, Japan, London, Belgium, France",20],["d","Dapitan","1892–1896: Exile",10]];
const WINGS={f:{wall:0x5a4735,rug:0x3a2416,tint:"#6b5a44",hi:"#c8a96a"},y:{wall:0x6b5438,rug:0x4a2e18,tint:"#8a6a3a",hi:"#d1a860"},a:{wall:0x4a3a28,rug:0x2e2014,tint:"#6a5636",hi:"#b89058"},d:{wall:0x362a1e,rug:0x22180f,tint:"#4a3a26",hi:"#9a7a4c"}};
const TIMELINE=[["1861","Born in Calamba, Laguna, on June 19."],["1880","His mother Teodora is arrested on a false charge."],["1882","Sails for Spain to continue his studies."],["1887","Noli Me Tangere is published in Berlin."],["1888","Travels through Japan and the United States to London."],["1891","El Filibusterismo is published in Ghent."],["1892","Returns to Manila, then is exiled to Dapitan."],["1896","Executed on December 30 at Bagumbayan, Manila."]];
/* Painted look of each portrait, same order as P. s=skin, h=hair, d=dress, st=style */
const LOOKS=[{s:"e",h:"#8d8d90",d:"#4a3a4a",st:"victorian"},{s:"e",h:"#2b1d16",d:"#b8788a",st:"victorian"},{s:"e",h:"#1f1712",d:"#8a6a9a",st:"victorian"},{s:"f",h:"#2b1d16",d:"#a04a52",st:"updo"},{s:"a",h:"#111111",d:"#b04a5a",st:"bun"},{s:"f",h:"#c49a5a",d:"#7a9a9a",st:"long"},{s:"f",h:"#8a5a2a",d:"#5a6a8a",st:"updo"},{s:"f",h:"#7a5636",d:"#c8b48a",st:"hat"},{s:"f",h:"#7a3a22",d:"#3a4a6a",st:"victorian",fr:1,bl:1}];
